variables:
- &no_web:
   - branch:
       exclude: website

clone:
  git:
    image: plugins/git
    settings:
      path: ${CI_WORKSPACE}/code
      lfs: false

steps:
  clone-website:
    image: plugins/git
    when: *no_web
    settings:
      path: ${CI_WORKSPACE}/website
      lfs: false
      branch: website
  build:
    image: barichello/godot-ci:4.1.3
    when: *no_web
    commands:
      - ls -la /root/.local/share/godot/templates
      - ls -la .
      - ls -la ./code
      - ls -la ./website
      - rm -r ./website/* || true
      - cd code/project
      - godot -v --headless --export-release "Web" ../../website/index.html
      - ls -lta ../../website
  deploy:
    image: appleboy/drone-git-push
    when: *no_web
    settings:
      branch: website
      local_ref: website
      path: website
