steps:
  build:
    when:
      - branch:
          exclude: website
    image: barichello/godot-ci:4.1.3
    commands:
      - ls -la /root/.local/share/godot/templates
      - ls -la .
      - mkdir -v -p build/web
      - cd project
      - godot -v --headless --export-release "Web" ../build/web/index.html
      - ls -lta ../build/web
