variables:
- &no_web:
   - branch:
       exclude: website

clone:
  clone-code:
    image: woodpeckerci/plugin-git
    settings:
      path: code
      lfs: false
  clone-website:
    image: woodpeckerci/plugin-git
    when: *no_web
    settings:
      path: website
      lfs: false
      branch: website
      sha: ''
      ref: refs/heads/website

steps:
  build:
    image: barichello/godot-ci:4.1.3
    when: *no_web
    commands:
      - ls -la /root/.local/share/godot/templates
      - ls -la .
      - ls -la ./code
      - ls -la ./website
      - rm -r ./website/* || true
      - cd code/project
      - godot -v --headless --export-release "Web" ../../website/index.html
      - ls -lta ../../website
  deploy:
    image: woodpeckerci/plugin-git
    when: *no_web
    commands:
      - cd website
      - git status
      - git branch -vv
      - git add .
      - git config user.name "${CI_COMMIT_AUTHOR}"
      - git config user.email "${CI_COMMIT_AUTHOR_EMAIL}"
      - git commit -m "Update website ${CI_COMMIT_SHA}"
      - git push
  # deploy:
  #   image: appleboy/drone-git-push
  #   when: *no_web
  #   settings:
  #     branch: website
  #     local_ref: website
  #     path: website
